import Link from "next/link";

const S={main:{maxWidth:1040,margin:"0 auto",padding:"36px 20px 72px",fontFamily:"system-ui, sans-serif",color:"#172033"} as React.CSSProperties,hero:{padding:"34px 38px",border:"1px solid #d9e2ef",borderRadius:20,background:"#f7faff"} as React.CSSProperties,nav:{display:"flex",flexWrap:"wrap",gap:8,margin:"22px 0"} as React.CSSProperties,chip:{padding:"8px 11px",border:"1px solid #cbd8e8",borderRadius:9,color:"#1557c0",textDecoration:"none",fontWeight:700,fontSize:14} as React.CSSProperties,section:{padding:"24px 4px",borderBottom:"1px solid #e2e8f0",lineHeight:1.65} as React.CSSProperties};
export default function Ayuda(){
return <main style={S.main}><Link href="/" style={{color:"#1557c0",fontWeight:700,textDecoration:"none"}}>← Volver a Tu Coach</Link>
<section style={S.hero}><div style={{fontSize:12,fontWeight:800,letterSpacing:1.4,color:"#1557c0"}}>CENTRO DE AYUDA · TU COACH</div><h1 style={{fontSize:38,margin:"8px 0 10px"}}>Cómo utilizar Tu Coach</h1><p style={{margin:0,color:"#53627a",fontSize:17}}>Guía para empezar a preparar tu oposición, practicar y entender tus resultados.</p></section>
<nav style={S.nav}>{[["primeros","Primeros pasos"],["cuenta","Cuenta y suscripción"],["pruebas","Simulacros y tests"],["resultados","Resultados"],["materiales","Materiales"],["faq","Preguntas frecuentes"]].map(([id,t])=><a key={id} href={"#"+id} style={S.chip}>{t}</a>)}</nav>
<section id="primeros" style={S.section}><h2>1. Primeros pasos</h2><ol><li>Crea tu cuenta o inicia sesión.</li><li>Si no recuerdas la contraseña, utiliza la recuperación para recibir un enlace de restablecimiento.</li><li>Desde tu cuenta puedes consultar el estado de tu prueba gratuita o suscripción.</li></ol><p>El inicio reúne tus convocatorias disponibles, pruebas pendientes y corregidas y actividad reciente.</p></section>
<section id="cuenta" style={S.section}><h2>2. Cuenta, prueba y suscripción</h2><p>La prueba gratuita dura 48 horas y permite utilizar la plataforma con límites en pruebas y descargas. Al terminar puedes activar una suscripción para mantener el acceso completo. Si una suscripción termina, puedes volver a suscribirte desde tu cuenta.</p><p>La disponibilidad de determinadas funciones depende del tipo y estado de acceso que tenga tu cuenta.</p></section>
<section id="pruebas" style={S.section}><h2>3. Simulacros y tests</h2><p><strong>Simulacro:</strong> reproduce la estructura completa disponible para una convocatoria. Puedes realizarlo en pantalla o descargar los PDF de preguntas y soluciones.</p><p><strong>Test:</strong> permite practicar por puntos del temario o por leyes y normas concretas. Elige convocatoria, número de preguntas y contenidos. Las pruebas se conservan para continuarlas, corregirlas o eliminarlas.</p><p>En pantalla puedes marcar A, B, C o D, dejar preguntas en blanco, usar el cronómetro y registrar opcionalmente tu nivel de seguridad.</p></section>
<section id="resultados" style={S.section}><h2>4. Corrección y análisis</h2><p>La corrección muestra nota, aciertos, fallos, preguntas sin contestar, puntos y tiempo empleado. Puedes revisar cada pregunta, tu respuesta y la opción correcta.</p><p>El rendimiento acumulado utiliza las pruebas conservadas y corregidas para agrupar resultados por tema, ley o norma y nivel de seguridad. Si modificas o eliminas una prueba, los datos se recalculan.</p></section>
<section id="materiales" style={S.section}><h2>5. Materiales y documentos</h2><p>En Materiales de estudio selecciona la convocatoria y, cuando corresponda, la ley o norma. Según disponibilidad, podrás descargar resúmenes, extractos o textos completos en PDF. Desde una prueba abierta también puedes descargar preguntas y soluciones.</p></section>
<section id="faq" style={S.section}><h2>6. Preguntas frecuentes</h2><h3>¿Puedo continuar una prueba?</h3><p>Las pruebas pendientes se pueden continuar y las corregidas se pueden volver a consultar.</p><h3>¿Por qué una prueba aparece en solo lectura?</h3><p>Algunas pruebas históricas se conservan para consulta y descarga, pero no admiten modificaciones.</p><h3>¿Qué ocurre si elimino una prueba?</h3><p>También se elimina su contribución a las estadísticas acumuladas.</p><h3>¿Debo comprobar la información oficial?</h3><p>Sí. La información de convocatorias, normas y plazos debe contrastarse siempre con la fuente oficial.</p></section>
<section style={{...S.section,borderBottom:"none"}}><h2>¿Necesitas más ayuda?</h2><p>Si no encuentras aquí la respuesta que necesitas, puedes ponerte en contacto con Tu Coach.</p><Link href="/contacto" style={{...S.chip,display:"inline-flex"}}>Contactar con Tu Coach →</Link></section></main>}