import Link from "next/link";
const S={main:{maxWidth:1040,margin:"0 auto",padding:"30px 20px 72px",fontFamily:"system-ui, sans-serif",color:"#172033"} as React.CSSProperties,hero:{padding:"34px 38px",border:"1px solid #d9e2ef",borderRadius:20,background:"#f7faff"} as React.CSSProperties,nav:{display:"flex",flexWrap:"wrap",gap:8,margin:"22px 0"} as React.CSSProperties,chip:{padding:"8px 11px",border:"1px solid #cbd8e8",borderRadius:9,color:"#1557c0",textDecoration:"none",fontWeight:700,fontSize:14} as React.CSSProperties,section:{padding:"24px 4px",borderBottom:"1px solid #e2e8f0",lineHeight:1.65} as React.CSSProperties};
export default function AyudaEmpleo(){return <main style={S.main}><Link href="/empleo" style={{color:"#1557c0",fontWeight:700,textDecoration:"none"}}>← Volver a Empleo público</Link><section style={S.hero}><div style={{fontSize:12,fontWeight:800,letterSpacing:1.4,color:"#1557c0"}}>CENTRO DE AYUDA · EMPLEO PÚBLICO</div><h1 style={{fontSize:38,margin:"8px 0 10px"}}>Cómo utilizar Empleo público</h1><p style={{margin:0,color:"#53627a",fontSize:17}}>Explora oportunidades administrativas, entiende sus plazos y mantén bajo seguimiento los procesos que te interesan.</p></section>
<nav style={S.nav}>{[["acceso","Acceso"],["explorar","Buscar oportunidades"],["ficha","Ficha y plazos"],["estados","Estados de inscripción"],["categorias","Tipos de oportunidad"],["seguimiento","Seguimiento"],["avisos","Novedades y correos"],["faq","Preguntas frecuentes"]].map(([id,t])=><a key={id} href={"#"+id} style={S.chip}>{t}</a>)}</nav>
<section id="acceso" style={S.section}><h2>1. Acceso</h2><p>Esta guía es pública. Para consultar las oportunidades y utilizar el seguimiento personal necesitas iniciar sesión con una cuenta que tenga acceso a Empleo público.</p></section>
<section id="explorar" style={S.section}><h2>2. Buscar oportunidades</h2><ol><li>Entra en Empleo público para ver el resumen de oportunidades y plazas.</li><li>Elige Generalitat Valenciana o una provincia para recorrer diputaciones y ayuntamientos.</li><li>Abre un organismo para consultar sus procesos.</li><li>Utiliza el filtro de inscripción abierta cuando quieras localizar procesos cuyo plazo esté confirmado como abierto.</li></ol></section>
<section id="ficha" style={S.section}><h2>3. Entender una ficha y sus plazos</h2><p>Las tarjetas y fichas reúnen, cuando constan, organismo, estado, plazas, tipo de proceso, turno, grupo o subgrupo, fecha de examen y etapa actual. Los plazos se muestran por separado cuando un proceso tiene más de uno.</p><p>Consulta las publicaciones y cambios registrados y utiliza <strong>Ver convocatoria oficial</strong> para acudir a la fuente de origen. Si aparece una advertencia sobre festivos locales, comprueba el plazo directamente con el organismo convocante.</p></section>
<section id="estados" style={S.section}><h2>4. Estados de inscripción</h2><p><strong>Inscripción abierta:</strong> existe un plazo confirmado actualmente abierto.</p><p><strong>Inscripción cerrada:</strong> el plazo conocido ha finalizado. Esto no significa necesariamente que el proceso selectivo haya terminado.</p><p><strong>Pendiente de publicación en BOE:</strong> Tu Coach todavía no ha confirmado la publicación en BOE necesaria para determinar el plazo.</p><p><strong>Sin plazo confirmado:</strong> no hay información suficiente para afirmar que la inscripción esté abierta.</p></section>
<section id="categorias" style={S.section}><h2>5. Oposiciones, bolsas y difícil cobertura</h2><p>Tu Coach puede presentar separadamente las <strong>oposiciones</strong> y otras oportunidades como <strong>bolsas de trabajo</strong> y <strong>anuncios de difícil cobertura</strong>. Esta organización facilita la consulta y puede variar según el acceso disponible en cada momento.</p></section>
<section id="seguimiento" style={S.section}><h2>6. Mi seguimiento</h2><p>Pulsa <strong>Seguir</strong> en una oportunidad para incorporarla a Mi seguimiento. Allí encontrarás las publicaciones y cambios relevantes que Tu Coach detecte después de que comenzaras a seguirla. Pulsa <strong>Dejar de seguir</strong> cuando ya no quieras mantenerla en tu listado.</p><p>El historial de novedades se muestra durante <strong>10 días desde su detección por Tu Coach</strong>.</p></section>
<section id="avisos" style={S.section}><h2>7. Novedades y correos</h2><p>Una <strong>novedad de seguimiento</strong> es una publicación o cambio relevante detectado después de empezar a seguir una oportunidad. Al entrar en Mi seguimiento, las novedades pendientes quedan vistas, aunque permanecen temporalmente en el historial.</p><p>Los avisos de seguimiento se envían únicamente a quienes siguen la oportunidad afectada. De forma separada, los suscriptores pueden recibir avisos sobre nuevas oportunidades incorporadas a Tu Coach, según las funciones a las que tengan acceso.</p></section>
<section id="faq" style={S.section}><h2>8. Preguntas frecuentes</h2><h3>¿Un proceso activo tiene necesariamente la inscripción abierta?</h3><p>No. El proceso puede continuar activo después de finalizar el plazo de solicitudes.</p><h3>¿Por qué falta una fecha?</h3><p>La ausencia de una fecha o dato significa que no está disponible o no se ha confirmado en la información mostrada.</p><h3>¿Tu Coach sustituye a la fuente oficial?</h3><p>No. La publicación del organismo convocante, su sede electrónica y el boletín oficial correspondiente prevalecen siempre.</p></section></main>}